import { DemoScenario, DemoType } from "@/types";

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: "whatsapp-chat-commerce",
    type: "whatsapp_chat",
    title: "Chat Commerce",
    titleEn: "Chat Commerce",
    subtitle: "Pesan barang langsung via WhatsApp",
    subtitleEn: "Order directly through WhatsApp",
    description: "Simulasikan workflow chat commerce lengkap — dari katalog produk, pengambilan pesanan, konfirmasi stok, hingga receipt digital.",
    descriptionEn: "Simulate a complete chat commerce workflow — from product catalog, order taking, stock confirmation, to digital receipt.",
    icon: "🛒",
    color: "#10b981",
    gradient: "from-emerald-500/20 to-teal-500/20",
    badge: "SIMULASI",
    badgeColor: "badge-simulation",
    persona: "Head of Trade Marketing",
    personaPosition: "PT Unilever Indonesia",
    kpis: [
      { label: "Conversion Rate", value: "23", unit: "%" },
      { label: "Avg. Order Value", value: "Rp 850", unit: "Rb" },
      { label: "Response Time", value: "<30", unit: "detik" },
    ],
    integrations: [
      { name: "WhatsApp Business Platform", logo: "wa" },
      { name: "Inventory System", logo: "erp" },
      { name: "Payment Gateway", logo: "pay" },
      { name: "CRM", logo: "crm" },
    ],
    steps: [
      { id: "1", type: "system", content: "Customer membuka chat WhatsApp ke akun resmi brand" },
      { id: "2", type: "bot_response", content: "Bot: \"Halo! Selamat datang di store brand kami 👋 Mau belanja apa hari ini? Ketik 'katalog' untuk melihat produk atau langsung ketik nama produk yang diinginkan.\"" },
      { id: "3", type: "user_input", content: "Saya mau beli 5 item promo terbaru untuk minggu ini" },
      { id: "4", type: "integration", content: "⚙️ WhatsApp Business Platform → Product Catalog API\n⚙️ Inventory System → Stock Check (real-time)\n⚙️ CRM → Customer Profile Lookup" },
      { id: "5", type: "bot_response", content: "Bot: \"Baik! Saya sudah cek stok terbaru. Berikut 5 item promo minggu ini:\n\n📦 [Promo 1] — Rp 45.000 (Stok: 120)\n📦 [Promo 2] — Rp 38.500 (Stok: 85)\n📦 [Promo 3] — Rp 52.000 (Stok: 200)\n📦 [Promo 4] — Rp 29.900 (Stok: 350)\n📦 [Promo 5] — Rp 61.000 (Stok: 90)\n\nTotal estimate: Rp 226.400\n\nKetik nomor promo untuk tambah ke keranjang, atau 'checkout' untuk langsung pesan.\"" },
      { id: "6", type: "user_input", content: "checkout" },
      { id: "7", type: "integration", content: "⚙️ Order Management → Create Order\n⚙️ WhatsApp Business Platform → Send Order Confirmation Template\n⚙️ CRM → Update Customer Transaction History" },
      { id: "8", type: "bot_response", content: "Bot: ✅ *PESANAN KONFIRMASI*\n\nToko: Centralmart Jakarta\nNo. Order: ORD-2026-0824-001\n\nItem:\n1x Promo Bundle Week-34\n\nTotal: Rp 226.400\nMetode: Cash on Delivery\n\nEstimasi delivery: 2-3 hari kerja\n\nKonfirmasi pesanan? Balas *YA* untuk proceed." },
      { id: "9", type: "user_input", content: "YA" },
      { id: "10", type: "system", content: "Pesanan terkonfirmasi → receipt dikirim via WhatsApp → CRM updated → inventory decremented" },
      { id: "11", type: "outcome", content: "OUTCOME: Order berhasil dibuat. WhatsApp receipt dikirim otomatis. Distributor/retailer mendapat notifikasi. CRM menyimpan full transaction history." },
    ],
    services: [
      { id: "wa-biz", name: "WhatsApp Business Platform", description: "Official WhatsApp Business API dengan verified business account, broadcast, dan templated messages" },
      { id: "chat-commerce", name: "Chat Commerce Engine", description: "Shopping cart, katalog produk, dan checkout flow yang berjalan di dalam percakapan WhatsApp" },
      { id: "crm-integration", name: "CRM Integration", description: "Integrasi real-time dengan CRM untuk customer profile, transaction history, dan segmentation" },
      { id: "erp-sync", name: "ERP/SFA/DMS Sync", description: "Sinkronisasi otomatis antara WhatsApp order dengan sistem inventory, SFA, dan DMS" },
    ],
    estimatedTime: 3,
    ctaLabel: "Coba Demo Chat Commerce",
    ctaLabelEn: "Try Chat Commerce Demo",
  },
  {
    id: "ai-chatbot-obrol",
    type: "ai_chatbot",
    title: "Ngobrol.ai",
    titleEn: "Ngobrol.ai AI Chatbot",
    subtitle: "AI chatbot untuk FAQ & support distributor",
    subtitleEn: "AI chatbot for distributor FAQ & support",
    description: "Demonstrasi AI chatbot yang menangani pertanyaan FAQ distributor dan retailer — dari status pengiriman, kebijakan retur, hingga informasi promo terbaru.",
    descriptionEn: "Demonstration of AI chatbot handling distributor and retailer FAQ — from shipping status, return policies, to latest promo information.",
    icon: "🤖",
    color: "#8b5cf6",
    gradient: "from-violet-500/20 to-purple-500/20",
    badge: "SIMULASI",
    badgeColor: "badge-simulation",
    persona: "Distributor Manager",
    personaPosition: "PT Astra International",
    kpis: [
      { label: "FAQ Resolution", value: "87", unit: "%" },
      { label: "CS Load Reduction", value: "65", unit: "%" },
      { label: "Response Time", value: "<3", unit: "detik" },
    ],
    integrations: [
      { name: "Ngobrol.ai", logo: "ngobrol" },
      { name: "Knowledge Base", logo: "kb" },
      { name: "WhatsApp", logo: "wa" },
      { name: "Helpdesk", logo: "help" },
    ],
    steps: [
      { id: "1", type: "system", content: "Distributor mengirim pesan ke WhatsApp Business Official Account" },
      { id: "2", type: "bot_response", content: "Ngobrol.ai: \"Halo! Saya asisten AI dari [Brand]. Ada yang bisa saya bantu hari ini?\"" },
      { id: "3", type: "user_input", content: "Status pengiriman PO-2026-0815是什么时候?" },
      { id: "4", type: "integration", content: "⚙️ Ngobrol.ai NLP Engine → Intent Recognition (shipping_status)\n⚙️ ERP Integration → PO Lookup\n⚙️ WhatsApp Business Platform → Response Delivery" },
      { id: "5", type: "bot_response", content: "Ngobrol.ai: \"Saya cek dulu ya... ✅\n\n*Status Pengiriman PO-2026-0815*\n\n📦 Status: *Dalam Perjalanan*\n🚚 Ekspedisi: JNE Reguler\n📍 Lokasi Terkini: Gudang Jakarta Timur\n📅 Estimasi Tiba: 27 Agustus 2026\n\nNo. Resi: JNE1234567890\nTracking: jne.co.id/JNE1234567890\n\nAda yang lain yang bisa saya bantu?\"" },
      { id: "6", type: "user_input", content: "Kalau ada barang rusak bagaimana proses retur nya?" },
      { id: "7", type: "integration", content: "⚙️ Ngobrol.ai NLP Engine → Intent Recognition (return_policy)\n⚙️ Knowledge Base → Return Policy Document\n⚙️ CRM → Customer Tier Lookup" },
      { id: "8", type: "bot_response", content: "Ngobrol.ai: \"Untuk proses retur, berikut langkah-langkahnya:\n\n📋 *Panduan Retur Barang*\n\n1️⃣ Foto barang rusak + invoice\n2️⃣ Kirim via WhatsApp ke nomor ini\n3️⃣ Tim kami akan approve dalam 1x24 jam\n4️⃣ Barang ditukar di lokasi pickup atau uang dikembalikan\n\n⚠️ *Catatan:* Retur max 7 hari setelah penerimaan. Untuk kategori tertentu (makanan/minuman) max 24 jam.\n\nApakah Anda ingin langsung initiate retur untuk PO-2026-0815?\"" },
      { id: "9", type: "user_input", content: "ya tolong initiate retur untuk PO itu" },
      { id: "10", type: "integration", content: "⚙️ CRM → Create Return Ticket\n⚙️ Helpdesk System → Assign Ticket to Returns Team\n⚙️ WhatsApp → Send Ticket Confirmation" },
      { id: "11", type: "bot_response", content: "Ngobrol.ai: \"✅ *Retur Berhasil Diinisiasi*\n\n🎫 Ticket #: RET-2026-0824-047\n📦 PO Reference: PO-2026-0815\n📝 Status: Menunggu Verifikasi\n👤 Assigned to: Returns Team\n\nTim kami akan menghubungi Anda dalam 1x24 jam untuk konfirmasi foto barang. Terima kasih atas pengertiannya!\"" },
      { id: "12", type: "outcome", content: "OUTCOME: Retur berhasil diinisiasi tanpa campur tangan manusia. Ticket otomatis terbuat di CRM. Distributor mendapat konfirmasi instan." },
    ],
    services: [
      { id: "ngobrol-ai", name: "Ngobrol.ai", description: "AI chatbot dengan NLP untuk pemahaman bahasa Indonesia natural, intent classification, dan entity extraction" },
      { id: "knowledge-base", name: "Knowledge Base Integration", description: "Auto-updating knowledge base yang sync dengan FAQ, SOP, dan kebijakan terbaru" },
      { id: "human-handoff", name: "Smart Human Handoff", description: "Otomatis escalate ke human agent saat AI confidence di bawah threshold" },
      { id: "omnichannel", name: "Omnichannel Inbox", description: "Semua percakapan dari WhatsApp, web, dan mobile masuk satu inbox terpadu" },
    ],
    estimatedTime: 4,
    ctaLabel: "Coba Demo Ngobrol.ai",
    ctaLabelEn: "Try Ngobrol.ai Demo",
  },
  {
    id: "robocall-payment",
    type: "robocall",
    title: "RoboCall Payment",
    titleEn: "RoboCall Payment Reminder",
    subtitle: "AI voice agent untuk pengingat pembayaran",
    subtitleEn: "AI voice agent for payment reminders",
    description: "Demonstrasi AI voice agent (RoboCall) untuk reminder pembayaran otomatis — dengan interactive voice response, payment confirmation, dan escalation.",
    descriptionEn: "Demonstration of AI voice agent (RoboCall) for automated payment reminders — with interactive voice response, payment confirmation, and escalation.",
    icon: "📞",
    color: "#f97316",
    gradient: "from-orange-500/20 to-amber-500/20",
    badge: "SIMULASI",
    badgeColor: "badge-simulation",
    persona: "Finance & Credit Manager",
    personaPosition: "PT Salim Group",
    kpis: [
      { label: "Collection Rate", value: "+34", unit: "%" },
      { label: "Call Success", value: "89", unit: "%" },
      { label: "Cost/Call", value: "Rp 850", unit: "" },
    ],
    integrations: [
      { name: "RoboCall", logo: "robocall" },
      { name: "ERP System", logo: "erp" },
      { name: "WhatsApp", logo: "wa" },
      { name: "Payment Gateway", logo: "pay" },
    ],
    steps: [
      { id: "1", type: "system", content: "📞 RoboCall Agent initiating outbound call...\n📱 Dialing: +6281-XXXX-7890\n🏢 Target: Finance Manager, PT Salim Group" },
      { id: "2", type: "bot_response", content: "[AUDIO PLAYBACK — IVR]\n\n\"Selamat pagi. Ini adalah panggilan otomatis dari [Brand]. Saya ingin berbicara dengan Bapak/Ibu Finance Manager regarding an outstanding payment. Tekan 1 untuk Connected, tekan 2 untuk Schedule Callback, tekan 3 untuk Request Detail via WhatsApp.\"" },
      { id: "3", type: "user_input", content: "[DTMF: 1]" },
      { id: "4", type: "system", content: "✅ Call connected — human answered" },
      { id: "5", type: "bot_response", content: "[AUDIO — Conversational AI]\n\n\"Terima kasih sudah mengangkat. Saya ingin menginformasikan bahwa terdapat tagihan yang belum dibayarkan dengan detail sebagai berikut:\n\n📋 Invoice: INV-2026-0724\n💰 Jumlah: Rp 127.500.000\n📅 Due Date: 20 Agustus 2026\n📅 Hari ini: 24 Agustus 2026\n⏰ Overdue: 4 hari\n\nApakah Bapak/Ibu dapat memproses pembayaran hari ini?\"" },
      { id: "6", type: "user_input", content: "Wah bisa, tapi bisakah kirim ulang nominal yang benar? Saya ragu dengan angka itu" },
      { id: "7", type: "bot_response", content: "[AUDIO]\n\n\"Baik, saya akan kirimkan detail lengkapnya via WhatsApp agar lebih jelas. Bisa saya minta konfirmasi nomor WhatsApp aktif Anda?\"" },
      { id: "8", type: "user_input", content: "0819-XXXX-1234" },
      { id: "9", type: "integration", content: "⚙️ RoboCall → Record Callback Preference\n⚙️ WhatsApp Business Platform → Send Payment Detail Template\n⚙️ ERP → Recalculate Outstanding (if any correction)\n⚙️ CRM → Update Contact Record" },
      { id: "10", type: "system", content: "✅ WhatsApp Detail Sent\n📱 +62819-XXXX-1234\n📋 Invoice: INV-2026-0724\n💰 Amount: Rp 127.500.000\n🔗 Payment Link: bit.ly/brand-pay-2026" },
      { id: "11", type: "bot_response", content: "[AUDIO]\n\n\"Baik, saya sudah kirimkan detail tagihan dan link pembayaran via WhatsApp ke nomor 0819-XXXX-1234. Silakan dicek dan apabila sudah transfer mohon konfirmasi via WhatsApp tersebut dengan kirim bukti transfer.\n\nApakah ada pertanyaan lain yang bisa saya bantu?\"" },
      { id: "12", type: "user_input", content: "Tidak ada, terima kasih" },
      { id: "13", type: "bot_response", content: "[AUDIO]\n\n\"Terima kasih. Have a great day. Sampai jumpa.\"\n\n📞 Call Ended\n⏱️ Duration: 2 menit 34 detik\n💰 Cost: Rp 850\n📊 Outcome: Callback Scheduled — Detail Sent" },
      { id: "14", type: "outcome", content: "OUTCOME: RoboCall berhasil收取 pembayaran overdue tanpa campur tangan manusia. Detail dikirim via WhatsApp. Call summary masuk ke CRM. Collection rate meningkat 34%." },
    ],
    services: [
      { id: "robocall", name: "RoboCall", description: "AI voice agent dengan text-to-speech dan speech recognition untuk outbound calls natural dan interaktif" },
      { id: "ivr", name: "IVR System", description: "Interactive Voice Response dengan DTMF detection dan conditional branching" },
      { id: "voice-analytics", name: "Voice Analytics", description: "Real-time sentiment analysis dan conversation intelligence untuk quality monitoring" },
      { id: "schedule-callback", name: "Scheduled Callback", description: "Sistem callback otomatis pada waktu yang disepakati caller" },
    ],
    estimatedTime: 4,
    ctaLabel: "Coba Demo RoboCall",
    ctaLabelEn: "Try RoboCall Demo",
  },
];

export function getDemoByType(type: DemoType): DemoScenario | undefined {
  return DEMO_SCENARIOS.find((s) => s.type === type);
}

export function getAllDemos(): DemoScenario[] {
  return DEMO_SCENARIOS;
}
